config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:index] do
    member do
      post :upload_to_google
    end
  end

  resource :oauth2, only: [:new] do
    get :callback
  end

  root to: 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oauth2s_controller.rb
class Oauth2sController < ApplicationController
  def new
    uri = ::URI.parse('https://accounts.google.com/o/oauth2/v2/auth')
    params = {
      client_id: Rails.application.credentials.google[:api][:client_id],
      scope: 'https://www.googleapis.com/auth/photoslibrary.appendonly',
      redirect_uri: callback_oauth2_url,
      response_type: 'code',
    }
    uri.query = ::URI.encode_www_form(params)

    redirect_to uri.to_s
  end

  def callback
    if params[:code].blank?
      redirect_to root_url, alert: 'Google連携がキャンセルされました。' and return
    end

    uri = ::URI.parse('https://www.googleapis.com/oauth2/v4/token')
    req_params = {
      code: params[:code],
      client_id: Rails.application.credentials.google[:api][:client_id],
      client_secret: Rails.application.credentials.google[:api][:client_secret],
      grant_type: 'authorization_code',
      redirect_uri: callback_oauth2_url,
    }
    res = ::Net::HTTP.post_form(uri, req_params)

    result = ::JSON.parse(res.body)
    session[:access_token] = result['access_token']

    redirect_to root_url, notice: 'Google連携に成功しました。'
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.with_attached_file.all.order(:id)
  end

  def upload_to_google
    @photo = Photo.with_attached_file.find(params[:id])

    upload_token = upload_image(@photo)
    logger.debug("upload token: #{upload_token}")
    result = create_media_item(upload_token)
    logger.debug("batchCreate result: #{result}")

    redirect_to root_path, notice: 'Googleフォトへのアップロードが完了しました。'
  end

  private

  def upload_image(photo)
    uri = ::URI.parse('https://photoslibrary.googleapis.com/v1/uploads')

    req = ::Net::HTTP::Post.new(uri)
    req['Authorization'] = "Bearer #{session[:access_token]}"
    req['Content-Type'] = 'application/octet-stream'
    req['X-Goog-Upload-File-Name'] = photo.file.blob.filename
    req.body = photo.file.blob.download

    res = ::Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
      http.request(req)
    end
    res.is_a?(::Net::HTTPSuccess) ? res.body : res.error!
  end

  def create_media_item(upload_token)
    uri = ::URI.parse('https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate')

    req = ::Net::HTTP::Post.new(uri)
    req['Authorization'] = "Bearer #{session[:access_token]}"
    req['Content-Type'] = 'application/json'
    req.body = {
      newMediaItems: [
        {
          description: "Google Photos API test",
          simpleMediaItem: {
            uploadToken: upload_token
          }
        }
      ]
    }.to_json

    res = ::Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
      http.request(req)
    end
    res.is_a?(::Net::HTTPSuccess) ? res.body : res.error!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GooglePhotoApiTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<h1>写真一覧</h1>

<% if flash[:notice].present? %>
  <p><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert].present? %>
  <p style="color: red;"><%= flash[:alert] %></p>
<% end %>

<%= button_to 'Google連携する', new_oauth2_path, method: :get %>

<div class="photos">
  <% @photos.each do |photo| %>
    <div class="photo">
      <p><%= photo.title %></p>
      <div class="image">
        <%= image_tag photo.file %>
      </div>
      <% if session[:access_token].present? %>
        <%= button_to 'Googleへアップロード', upload_to_google_photo_path(photo) %>
      <% end %>
    </div>
  <% end %>
</div>